module.exports = {
  AUTH: {
    USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
    INVALID_PASSWORD: "AUTH_INVALID_PASSWORD",
    TOKEN_INVALID: "AUTH_TOKEN_INVALID",
    SUCCESS: "AUTH_SUCCESS",
    CREATE_ADMIN_FORBIDDEN: "USER_CREATE_ADMIN_FORBIDDEN",
    SELF_DEACTIVATION_FORBIDDEN: "AUTH_SELF_DEACTIVATION_FORBIDDEN",
  },
  REGISTER: {
    USERNAME_EXISTS: "REGISTER_USERNAME_EXISTS",
    EMAIL_EXISTS: "REGISTER_EMAIL_EXISTS",
    INVALID_ROLE: "REGISTER_INVALID_ROLE",
    SUCCESS: "REGISTER_SUCCESS",
    FAILED: "REGISTER_FAILED",
  },
  BAR: {
    NOT_FOUND: "BAR_NOT_FOUND",
    CREATE_SUCCESS: "BAR_CREATE_SUCCESS",
    CREATE_FAILED: "BAR_CREATE_FAILED",
    UPDATE_SUCCESS: "BAR_UPDATE_SUCCESS",
    UPDATE_FAILED: "BAR_UPDATE_FAILED",
  },
  FACULTAD: {
    NOT_FOUND: "FACULTAD_NOT_FOUND",
    CREATE_SUCCESS: "FACULTAD_CREATE_SUCCESS",
    CREATE_FAILED: "FACULTAD_CREATE_FAILED",
    UPDATE_SUCCESS: "FACULTAD_UPDATE_SUCCESS",
    UPDATE_FAILED: "FACULTAD_UPDATE_FAILED",
  },
  PROFILE: {
    UPDATE_SUCCESS: "PROFILE_UPDATE_SUCCESS",
    UPDATE_FAILED: "PROFILE_UPDATE_FAILED",
    NOT_FOUND: "PROFILE_NOT_FOUND",
    PASSWORD_MISMATCH: "PROFILE_INVALID_PASSWORD",
    PASSWORD_UPDATE_SUCCESS: "PROFILE_PASSWORD_UPDATE_SUCCESS",
  },
  REVIEW: {
    CREATE_SUCCESS: "REVIEW_CREATE_SUCCESS",
    CREATE_FAILED: "REVIEW_CREATE_FAILED",
  },
  SERVER: {
    UNKNOWN: "SERVER_UNKNOWN_ERROR",
  },
};
